"""create tasks table

Revision ID: e8498f365565
Revises:
Create Date: 2026-08-27 03:31:01.301968

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "e8498f365565"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
